### ISSUE TITLE
Character set and glyph count

### ISSUE THREAD

**Issue by m4rc1e** [m4rc1e/xiaowei#1]
@davelab6 LGTM. There's only 7k glyphs though. I'm guessing this family is Chinese Simplified?

![desktop_os_x_high_sierra_safari_11 1_](https://user-images.githubusercontent.com/7525512/48500588-1d754180-e833-11e8-85c3-3e9768da7a9d.gif)
**OS X Sierra**

![desktop_windows_7_ie_9 0_](https://user-images.githubusercontent.com/7525512/48500606-25cd7c80-e833-11e8-96fe-3368b63f6766.jpg)
_Win7 IE 9_

**Comment by davelab6** [comment]
Correct, direct from Beijing :)
